#!/bin/sh
set -e

nixinstall() {
	mkdir -p "$HOME"/.vim
	cp vimrc "$HOME"/.vimrc
	cp prettierrc "$HOME"/.prettierrc
	cp stylelintrc "$HOME"/.stylelintrc
	cp lua-format "$HOME"/.lua-format
	cp ptop.cfg "$HOME"/.ptop.cfg
  cp clang-format "$HOME"/.clang-format
	for i in backup swap view undo; do
		mkdir -p "$HOME"/.vim/cache/$i
	done
}

wininstall() {
	cp vimrc "$HOME"/_vimrc
	mkdir -p "$HOME"/vimfiles
	cp prettierrc "$HOME"/.prettierrc
	cp stylelintrc "$HOME"/.stylelintrc
	cp lua-format "$HOME"/.lua-format
	cp ptop.cfg "$HOME"/.ptop.cfg
  cp clang-format "$HOME"/.clang-format
	cp -R configs/* "$HOME"/vimfiles
	mkdir -p "$HOME"/vimfiles/pack/plugins/start
	cp -R plugins/* "$HOME"/vimfiles/pack/plugins/start/
}

case $(uname -s | awk '{print tolower($0)}') in
linux* | *bsd* | *darwin*)
	nixinstall
	;;
mingw64*)
	wininstall
	;;
*)
	printf 'What are you doing?\n'
	;;
esac
